# Optimization results visualization

In [48]:
# TODO :
# - Couleurs graphes
# - Date en axe x
# - Trouver la liste des chemins fichiers excels des résultats

In [49]:
import pandas as pd
import plotly.graph_objects as go
import plotly.io as pio
pio.renderers.default = "notebook"
import datetime
import os

### Loading the results data

In [ ]:
Tmax = 168 #optimization for 1 week (7*24=168 hours)
Tmaxmax = Tmax + 24

SCENARIO_FOLDER = './sc_ref/'
INPUT_PATH = os.path.join(SCENARIO_FOLDER + 'inputs.xlsx')

def load_assets():
    return pd.read_excel(INPUT_PATH, sheet_name="ASSETS").set_index('Name')

def load_timeseries():
    return pd.read_excel(INPUT_PATH, sheet_name="TIMESERIES")

def load_e_avail():
    return pd.read_excel(INPUT_PATH, sheet_name="E_AVAIL")

def load_assets_cost():
    return pd.read_excel(INPUT_PATH, sheet_name="ASSETS_COST")

def read_results():
    list_p_out = []
    list_p_in = []
    list_stock_e = []
    list_assets_state = []
    list_costs = []

    excel_files = [os.path.join(SCENARIO_FOLDER + f'results_semaine_{n}.xlsx') for n in range(52)]#, './results_semaine_1.xlsx']
    for week, excel_file in enumerate(excel_files) :
        for (sheet, list_df) in [("P_OUT", list_p_out), ("P_IN", list_p_in), ("STOCK_E", list_stock_e), ("COSTS", list_costs)]:
            df = pd.read_excel(excel_file, sheet_name=sheet)
            df["Time"] = df["Time"] + Tmax*week
            df = df.set_index("Time")
            list_df.append(df)
        list_assets_state.append(pd.read_excel(excel_file, sheet_name="ASSETS_STATE").set_index('asset_name'))
    
    # Fusionner les résultats des différentes semaines et enlever les valeurs des anneaux de garde
    df_p_out = pd.concat(list_p_out).loc[lambda d: ~d.index.duplicated(keep="last")]
    df_p_in = pd.concat(list_p_in).loc[lambda d: ~d.index.duplicated(keep="last")]
    df_stock_e = pd.concat(list_stock_e).loc[lambda d: ~d.index.duplicated(keep="last")]
    df_costs = pd.concat(list_costs).loc[lambda d: ~d.index.duplicated(keep="last")]
    df_assets_state = pd.concat(list_assets_state)

    return df_p_out, df_p_in, df_stock_e, df_assets_state, df_costs

def x_absciss(df):
    start=datetime.datetime(2026,7,4,0,0,0)
    return pd.date_range(start, start + datetime.timedelta(hours=len(df.index)), freq=datetime.timedelta(hours=1))

In [51]:
df_p_out, df_p_in, df_stock_e, df_assets_state, df_costs = read_results()

In [52]:
df_assets = load_assets()
df_assets.head()

,energy_in,energy_out,region,avail,pmax,pmin,dmin,on_init,h_on,h_off,efficiency,emax,e_init,price,family
Name,,,,,,,,,,,,,,,
Nuclear_1,NaN,elec,NaN,1,900.0,300,24,0,0,24,1.0,0,0,12,disp
Nuclear_2,NaN,elec,NaN,1,900.0,300,24,0,0,24,1.0,0,0,12,disp
Nuclear_3,NaN,elec,NaN,1,900.0,300,24,0,0,24,1.0,0,0,12,disp
Nuclear_4,NaN,elec,NaN,1,900.0,300,24,0,0,24,1.0,0,0,12,disp
Nuclear_5,NaN,elec,NaN,1,1300.0,330,24,0,0,24,1.0,0,0,12,disp

In [53]:
df_timeseries = load_timeseries()
df_timeseries.index = df_timeseries.index + 1
df_timeseries = df_timeseries.loc[:len(df_p_out)]

In [54]:
df_e_avail = load_e_avail()
df_e_avail

,Date,Heure,EMIN_STEP_8_PUMPS,EMAX_STEP_8_PUMPS,EMIN_Gas_storage_n,EMAX_Gas_storage_n,EMIN_Gas_storage_s,EMAX_Gas_storage_s,Unnamed: 8,Unnamed: 9
0,2026-07-04,00:00:00,0.0,201600.0,3300000.0,8400000.0,3300000.0,8400000.0,NaN,Hypothèse répartition pl. actifs.
1,2026-07-04,01:00:00,0.0,201600.0,3300000.0,8400000.0,3300000.0,8400000.0,NaN,Prix ?
2,2026-07-04,02:00:00,0.0,201600.0,3300000.0,8400000.0,3300000.0,8400000.0,NaN,NaN
3,2026-07-04,03:00:00,0.0,201600.0,3300000.0,8400000.0,3300000.0,8400000.0,NaN,NaN
4,2026-07-04,04:00:00,0.0,201600.0,3300000.0,8400000.0,3300000.0,8400000.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
8755,NaT,NaN,NaN,NaN,3240000.0,8370000.0,3240000.0,8370000.0,NaN,NaN
8756,NaT,NaN,NaN,NaN,3240000.0,8370000.0,3240000.0,8370000.0,NaN,NaN
8757,NaT,NaN,NaN,NaN,3240000.0,8370000.0,3240000.0,8370000.0,NaN,NaN
8758,NaT,NaN,NaN,NaN,3240000.0,8370000.0,3240000.0,8370000.0,NaN,NaN
8759,NaT,NaN,NaN,NaN,3240000.0,8370000.0,3240000.0,8370000.0,NaN,NaN

### Building graphs

In [55]:
import plotly.express as px

# fig = px.colors.diverging.swatches()
# fig.show()

colors = {
    'interconnexion' : px.colors.diverging.RdGy[8],
    'PV' : px.colors.diverging.Portland[2],
    'Hydro' : px.colors.diverging.balance[2],
    'Wind' : px.colors.diverging.RdYlGn[8],
    'Waste' : px.colors.diverging.Earth[0],
    'Bio' : px.colors.diverging.delta[9],
    'tank' : px.colors.diverging.Spectral[10],
    'STEP' : px.colors.diverging.Spectral[10],
    'LOAD' : px.colors.diverging.RdYlGn[0],
    'CCG' : px.colors.diverging.Spectral[3],
    'CHP' : px.colors.diverging.Portland[3],
    'TAC' : px.colors.diverging.Spectral[3],
    'Pyro' : px.colors.diverging.Spectral[3],
    'Electrolizer' : px.colors.diverging.Spectral[3],
    'Methan' : px.colors.diverging.Spectral[2],
    'Vapo' : px.colors.diverging.Spectral[2],
    'Coal' : px.colors.diverging.RdGy[9],
    'Fioul' : px.colors.diverging.RdGy[8],
    'Nuclear' : px.colors.diverging.delta[6],
    'LNG' : px.colors.diverging.Tropic[6],
    'default' : px.colors.diverging.Picnic[8]
}

def get_color(description:str):
    for t in colors.keys():
        if t in description:
            return colors[t]
    return colors['default']

In [ ]:
for energy_vector, region in [('gas', 'n'), ('gas', 's'), ('h2', 'n'), ('h2', 's'), ('elec', None)]:
    fig = go.Figure()

    # Fatal load/production
    region_filter = {'n': 'NORTH', 's': 'SOUTH', None: ''}
    for fatal in [col for col in df_timeseries.columns if (((energy_vector).upper() in col) and (region_filter[region] in col))]:        
        if 'LOAD' in fatal :
            fig.add_trace(go.Bar(
                    x=x_absciss(df_timeseries),
                    y=-df_timeseries[fatal],
                    # base=0,
                    marker_color=get_color(fatal),
                    name=f"{fatal}"
                ))
        else :
            fig.add_trace(go.Bar(
                    x=x_absciss(df_timeseries),
                    y=df_timeseries[fatal],
                    # base=0,
                    marker_color=get_color(fatal),
                    name=f"P_out {fatal}"
                ))

    # Consuming assets
    for asset in df_assets[(df_assets['energy_in']==energy_vector) & (region is None or df_assets['region']==region)].index:
        fig.add_trace(go.Bar(
                x=x_absciss(df_p_in),
                y=-df_p_in[asset],
                # base=0,
                marker_color=get_color(asset),
                name=f"P_in {asset}"
            ))

    # Producing assets
    subset = df_assets[
        (df_assets['energy_out'] == energy_vector)
        & (region is None or df_assets['region'] == region)
    ].copy()

    subset['order'] = subset['family'].map({'inter': 0, 'disp': 1}).fillna(2)
    subset['asset_name'] = subset.index

    producing_assets = (
        subset
        .sort_values(
            by=['order', 'asset_name'],
            ascending=[True, False]   # ordre normal sur family, inverse alphabétique sur nom
        )
        .index
        .tolist()
    )
    
    for asset in producing_assets:
        fig.add_trace(go.Bar(
                x=x_absciss(df_p_out),
                y=df_p_out[asset],
                # base=0,
                marker_color=get_color(asset),
                name=f"P_out {asset}"
            ))
        
    # Storage assets
    for storage in df_assets[(df_assets['energy_out']==energy_vector) & (df_assets['family']=='stock') & (region is None or df_assets['region']==region)].index:
        fig.add_trace(go.Scatter(
                x=x_absciss(df_stock_e),
                y=100 * df_stock_e[storage]/df_assets['emax'][storage],
                name=f"SOC {storage}",
                marker_color=get_color(asset),
                mode='lines', yaxis="y2"
            ))
        
        # EMIN
        fig.add_trace(go.Scatter(
                x=x_absciss(df_e_avail),
                y=100 * df_e_avail["EMIN_"+storage]/df_assets['emax'][storage],
                name=f"EMIN {storage}",
                marker_color=get_color(asset),
                mode='lines', yaxis="y2",
                line_dash="dot",
                visible="legendonly"
            ))
        
        # EMAX
        fig.add_trace(go.Scatter(
                x=x_absciss(df_e_avail),
                y=100 * df_e_avail["EMAX_"+storage]/df_assets['emax'][storage],
                name=f"EMAX {storage}",
                marker_color=get_color(asset),
                mode='lines', yaxis="y2",
                line_dash="dot",
                visible="legendonly"
            ))
        
    # Imports/exports
    other_region = {'n':'s', 's':'n'}
    if region :
        port = f"{energy_vector.capitalize()}_interconnexion_{other_region[region].upper()}"
        diff = df_p_in[port] - df_p_out[port]
        df_p_in[port] = diff.clip(lower=0)
        df_p_out[port] = (-diff).clip(lower=0)
        
        fig.add_trace(go.Bar(
                x=x_absciss(df_p_in),
                y=df_p_in[port],
                # base=0,
                marker_color=get_color(port),
                name=f"Import {port}"
            ))
        fig.add_trace(go.Bar(
                x=x_absciss(df_p_in),
                y=-df_p_out[port],
                # base=0,
                marker_color=get_color(port),
                name=f"Export {port}"
            ))


    fig.update_layout(
        title=f"{energy_vector.capitalize()} management in {region_filter[region].capitalize()} Zootopia (producer convention)",
        xaxis_title="Time",
        yaxis=dict(
            title="Power [MW]",
            side="left",
            ticksuffix=" MW"
        ),
        yaxis2=dict(
            title="State Of Charge [%]",
            overlaying="y",
            side="right",
            showgrid=False,
            range=[0, 100],
            ticksuffix=" %"
        ),
        barmode='relative',
        template = 'plotly_dark',
        bargap = 0,
    )
    fig.update_traces(marker_line_width=0, selector=dict(type="bar"))

    # fig.show()
    fig.write_html(os.path.join(SCENARIO_FOLDER, SCENARIO_FOLDER.split("/")[1]+f"_{energy_vector}_{region}.html"))

### Costs

In [ ]:
df_costs.sum()

Electrolyzer         8.336789e+06
Biomass              0.000000e+00
Wind_onshore         0.000000e+00
CHP_S                2.136817e+06
Coal_3               2.946834e+07
Fioul_2              5.669633e+06
CCG_6                5.725271e+06
Hydro_FO             0.000000e+00
STEP_8_PUMPS         0.000000e+00
Pyrogazeification    3.579729e+08
Methanizer_1         8.653482e+08
Nuclear_6            7.966693e+07
Nuclear_1            6.267771e+07
Nuclear_5            9.815966e+07
Coal_2               2.902979e+07
CHP_N                1.729968e+06
CCG_5                5.816027e+06
Fioul_1              3.932442e+06
Waste                0.000000e+00
Coal_4               3.151434e+07
Vaporeformer         8.179070e+06
CCG_2                5.029954e+06
CCG_1                5.299782e+06
CCG_3                4.863474e+06
Nuclear_4            7.013369e+07
CCG_7                6.247961e+06
TAC_2                1.296150e+05
CCG_4                6.197513e+06
Nuclear_3            7.039023e+07
Hydro_lake           0.000000e+00
Wind_offshore        0.000000e+00
LNG_imports          4.264403e+09
PV                   0.000000e+00
TAC_1                1.612243e+05
Coal_1               3.176036e+07
Nuclear_2            7.046595e+07
Methanizer_2         4.328332e+08
UNS                  4.414556e+05
EXC                  5.886016e+03
BAND_MIN             0.000000e+00
BAND_MAX             4.750130e+05
TOTAL                6.564202e+09
dtype: float64

In [ ]:
fig = go.Figure()

for cost in [col for col in df_costs.columns if not(col=='TOTAL')]:     
    fig.add_trace(go.Bar(
                        x=x_absciss(df_costs),
                        y=df_costs[cost],
                        # base=0,
                        name=f"{cost}"
                    ))

    fig.update_layout(
        title=f"Costs",
        xaxis_title="Time",
        yaxis=dict(
            title="Cost [€]",
            side="left",
            ticksuffix=" €"
        ),
        barmode='relative',
        template = 'plotly_dark',
        bargap = 0,
    )
    fig.update_traces(marker_line_width=0, selector=dict(type="bar"))

# fig.show()
fig.write_html(os.path.join(SCENARIO_FOLDER, "Costs.html"))